### ISSUE TITLE
HMR not working on new install?

### ISSUE THREAD

**Issue by swthate** [chasegiunta/craft-vue-tailwind#1]
Hiya. I did a new install of `craft-vue-tailwind` and followed the setup instructions (installed AssetRev, ran npm install (with latest node and npm versions), initialized tailwind, added the shadowLookup experiment to tailwind's conf file, and the site loads correctly after running `npm run dev`. Before getting started I also made sure I had the latest `@vue/cli` installed and uninstalled any old `vue-cli` versions.

However, with the `dev` script still running, if I make a change to a Vue component or to `app.css` the script informs me of the change correctly, but the page doesn't "refresh" itself.

Was there a step I missed along the way?

Thanks!

**Comment by swthate** [comment]
Update:

The browser's console shows two errors repeating over and over: `Invalid Host/Origin header` and `[WDS] Disconnected!` It's saying both of these are being reported by `client?1ed0` lines 174 and 177.

Looks like these are messages/errors inside a `var onSocketMsg` object. Not sure where to start investigating the `Invalid Host/Origin header` error. The local environment being used for this is Homestead, if that helps.

**Comment by swthate** [comment]
Another update and possible resolution:

A lot of other issues reported by people across the GitHub universe suggested adding `disableHostCheck: true` to the `devServer` object in Webpack config (or `vue.config.js` in our case).

That suppressed or fixed the errors and HMR is now working!

However... the Webpack docs have this to say about `disableHostCheck`:

> When set to true this option bypasses host checking. THIS IS NOT RECOMMENDED as apps that do not check the host are vulnerable to DNS rebinding attacks.

In this use case is this "vulnerability" confined to my local setup--making that vulnerability irrelevant? 🤔

**Comment by TomDeSmet** [comment]
I had the same issue, thank you for the workaround.

**Comment by chasegiunta** [comment]
@swthate interesting! I actually wasn't getting any browser console errors, but HMR definitely wasn't working in my latest project. I believe you're right about the vulnerability only being local. I think another workaround I had seen (just leaving here for reference) was placing this line:
```
__webpack_public_path__ = 'http://localhost:8080/'
```
in the `main.js` file .

I went ahead and updated that file with `disableHostCheck`. https://github.com/chasegiunta/craft-vue-tailwind/commit/16e132de1c2ff6a427817fd9e44a1e14a698c929
