### ISSUE TITLE
Unable to add object to `window` after 3.0.0 upgrade

### ISSUE THREAD

**Issue by swthate** [chasegiunta/craft-vue-tailwind#4]
I synced my fork with the 3.0.0 release and I have everything working now, I think, except this last part.

In my base template I have a twig object with some Craft info that I then json encode and put into a `Craft` object on `window` so I can get things like the csrf Token:

	{% set jsCraft = {
		apiUrl: alias('@web') ~ '/api',
		baseUrl: alias('@web'),
		csrfTokenName: craft.app.config.general.csrfTokenName,
		csrfToken: craft.app.request.csrfToken
	} %}
	<script type="text/javascript">
      window.Craft = {{ jsCraft|json_encode|raw }};
	</script>

But `Craft` never gets added to `window`. It keeps coming up as `undefined`. Is there something obvious that I've missed that's new in 3.0.0 that might make this no longer work for some reason? Or maybe there's a better way to do this now?

**Comment by chasegiunta** [comment]
I just ran your snippet no issue.

![image](https://user-images.githubusercontent.com/1377169/59166298-d65fde00-8aed-11e9-997a-b39b7ff3e06a.png)

**Comment by swthate** [comment]
Works for me too on a brand new project with the 3.0.0 repo. Something else is obviously not working. I tried blasting away `node_modules` and running `npm install` again hoping that would magically fix something goofy, but it didn't.

I wish I knew what it was. But I know I can just start over with the new release and go from there at least.
