### ISSUE TITLE
How to generate both manifest.json and manifest-legacy.json on build?

### ISSUE THREAD

**Issue by slebbo** [chasegiunta/craft-vue-tailwind#6]
In the twigpack config file, both legacy and modern manifest files are defined. But I haven't figured out how to output them both with this setup, I just get either or when changing the `VUE_CLI_MODERN_MODE` environment variable.

**Comment by chasegiunta** [comment]
@slebbo You need to be running `build` with the `--modern` flag. Are you assets still running without it? I think I was unsure on whether to make the default build script use modern or not.

**Comment by slebbo** [comment]
Yay! That flag totally solved it! 
Without that flag, it only generates one file which later on throws an error in Twigpack which, afaik, needs both files in order to output anything at all (that was my case however).

**Comment by chasegiunta** [comment]
@slebbo Interesting! I wasn’t experiencing that. IIRC, in my case, if the legacy manifest didn’t exist, Twigpack didn’t throw any errors. I’ll push an update tomorrow to default the `build` command to use the modern flag.
